feat: frontend OAuth
pokt-foundation/portal pull request #339
Opened 2022-03-14 14:43 UTC by jhodak

setting up OAuth with a controller to determine whether the user is using OAuth or legacy login methods

2022-03-28 13:50 UTC, Evalir requested changes
First review round :).

A few things about code quality, and the way we're approaching things:

2022-03-28 13:50 UTC, Evalir commented on packages/backend/src/App.ts
> +  ALLOWED_DOMAINS.push('http://localhost:3004')
Why are we pushing alternative domains? This should not be needed. If you're getting a port over 3000 you have something running that shouldn't be.

2022-03-28 13:50 UTC, Evalir commented on packages/backend/src/environment.ts
> +    return process.env.ALLOWED_DOMAINS?.split(',') ?? ['http://localhost:3001']
```suggestion
    return process.env.ALLOWED_DOMAINS?.split(',') ?? ['http://localhost:3000']
```

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/contexts/flagsContext.tsx
> +    authHeaders:
Just to confirm: We _will_ phase this out for a 100% Auth0 solution once we've performed the migration needed, right?

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/hooks/application-hooks.ts
> +
Let's remove this extra line.

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/hooks/application-hooks.ts
> +
Let's also remove this extra line.

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/contexts/flagsContext.tsx
> +  const [hookState, setHookState] = useState({
Also, q: why `hookState`? It might be better to call it `flags`. Reading the code later it isn't obvious what this is doing.

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/hooks/application-hooks.ts
> +      let path = null
Instead of using `let`, let's just use `const` and a ternary to also be more concise. As you will find out, I'm not a fan of `let` at all. 😄

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/hooks/network-hooks.ts
> +
:)

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/hooks/network-hooks.ts
> +
:)

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/hooks/network-hooks.ts
> +
:)

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/screens/Dashboard/Dashboard.tsx
> +  console.log(appsLoading, userApps, token, userLoading, 'Auth Loaded')
Let's remember to remove this before merging.

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/screens/Dashboard/NavigationBar.tsx
> +// import axios from 'axios'
Let's just remove the line instead of commenting it.

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/screens/Dashboard/NavigationBar.tsx
> +// import env from '../../environment'
Ditto

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/screens/Dashboard/Network/NetworkStatus.tsx
> +// import { useAuth0 } from '@auth0/auth0-react'
I assume we'll remove these after we're out of the draft state :).

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/src/screens/Onboarding/Login.jsx
> +  React.useEffect(() => {
Let's import `useEffect` instead of calling it with `React`.

2022-03-28 13:50 UTC, Evalir commented on packages/frontend/vite.config.ts
> +    port: 3001,
```suggestion
    port: 3000,
```

2022-05-10 14:06 UTC, jhodak commented on packages/backend/src/App.ts
> +  ALLOWED_DOMAINS.push('http://localhost:3004')
This has been changed only allows 3001

2022-05-10 14:06 UTC, jhodak commented on packages/backend/src/db.ts
> +  'mongodb://mongouser:mongopassword@localhost:27017/gateway?authSource=admin&authMechanism=SCRAM-SHA-256&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false'
This has been changed, but the -testnet will need to be updated in a separate PR

2022-05-10 14:08 UTC, jhodak commented on packages/backend/src/environment.ts
> +    return process.env.FRONTEND_URL || 'http://localhost:3001'
backend API's run on port 3000 - so it is not available to run the frontend, and in order to remove potential conflicts for folks depending on which order they build and run, just changed this universally to the frontend always running on 3001, as other folks would run into the same thing.

2022-05-10 14:08 UTC, jhodak commented on packages/backend/src/environment.ts
> +    return process.env.ALLOWED_DOMAINS?.split(',') ?? ['http://localhost:3001']
same as above

2022-05-10 14:10 UTC, jhodak commented on packages/frontend/src/contexts/flagsContext.tsx
> +    authHeaders:
Yes, auth0 will be the source of truth in the future.  But in the immediate future having a fallback is the desired state until we are 100% sure auth0 is functioning exactly as expected and we iron out any potential conflicts between different systems/analytics/etc.

2022-05-10 14:11 UTC, jhodak commented on packages/frontend/src/hooks/application-hooks.ts
> +
this has since been removed

2022-05-10 14:18 UTC, jhodak commented on packages/frontend/src/hooks/network-hooks.ts
> +
already updated

2022-05-10 14:18 UTC, jhodak commented on packages/frontend/src/hooks/network-hooks.ts
> +
already updated

2022-05-10 14:19 UTC, jhodak commented on packages/frontend/src/hooks/network-hooks.ts
> +
updated

2022-05-10 14:19 UTC, jhodak commented on packages/frontend/src/screens/Dashboard/Dashboard.tsx
> +  console.log(appsLoading, userApps, token, userLoading, 'Auth Loaded')
updated

2022-05-10 14:21 UTC, jhodak commented on packages/frontend/src/screens/Dashboard/NavigationBar.tsx
> +// import env from '../../environment'
same as above - still necessary at the moment

2022-05-10 14:22 UTC, jhodak commented on packages/frontend/src/screens/Dashboard/Network/NetworkStatus.tsx
> +// import { useAuth0 } from '@auth0/auth0-react'
it is necessary to have it in currently -- updated code looks different

2022-05-10 14:23 UTC, jhodak commented on packages/frontend/src/screens/Onboarding/Login.jsx
> +  React.useEffect(() => {
updated code looks different - comment no longer applicable

2022-05-10 14:24 UTC, jhodak commented on packages/frontend/vite.config.ts
> +    port: 3001,
removed the conflict between backend apis running on 3000 and frontend also trying to run on 3000 - simplified things by just moving frontend to 3001 permanently

2022-05-13 16:09 UTC, merged