Hodak/t 1091 feature flags
pokt-foundation/portal pull request #349
Opened 2022-03-24 13:00 UTC by jhodak

Adding feature flags controller and flags file
no flags currently implemented - no functionality effected on website

2022-03-28 14:21 UTC, jhodak commented on packages/frontend/src/contexts/flagsContext.tsx
> +    <FlagContext.Provider value={{ hookState, updateHookState }}>
updated with some memoization

2022-03-31 15:51 UTC, Evalir requested changes
A few comments about readability and the usage of `useMemo`

2022-03-31 15:51 UTC, Evalir commented on packages/frontend/src/contexts/flagsContext.tsx
> +export function useFlag() {
Hmm so, I think the name of the function is a tad misleading. You're not accessing the flag, but rather the context that holds the flag. Maybe we should call it `useFlags`?
```suggestion
export function useFlags() {
```

2022-03-31 15:51 UTC, Evalir commented on packages/frontend/src/contexts/flagsContext.tsx
> +    const [hookState, setHookState] = useState({
I think I said the same thing in the Auth0 PR, but, the `hookState` name is not very informative, and when you're using it in other code it might be confusing to see `hookState` instead of something like `flags`. How about renaming everything to `flags` and `setFlags`?

2022-03-31 15:51 UTC, Evalir commented on packages/frontend/src/contexts/flagsContext.tsx
> +    const updateHookState = (key: string, value: unknown) => {
With the comment above, I'd call this `updateFlag`

2022-03-31 15:51 UTC, Evalir commented on packages/frontend/src/contexts/flagsContext.tsx
> +)
`useMemo` is being used wrong here. You shouldn't return a memoization of the return value of the hook. You can return everything normally, and just memoize the `value` part before returning it, like this: https://github.com/pokt-foundation/portal/blob/mvp/packages/frontend/src/contexts/UserContext.tsx#L60-L86

2022-03-31 15:54 UTC, Evalir commented on packages/frontend/src/contexts/flagsContext.tsx
> +
Let's remove this extra line.

2022-03-31 17:04 UTC, jhodak commented on packages/frontend/src/contexts/flagsContext.tsx
> +    const [hookState, setHookState] = useState({
Going to rename to - `flagState` and `setFlagState` -- reason being that it is truly a state, and that it becomes useful knowing you are accessing a state, especially when you access it and will likely be going to use flagState.flags.someProperty it ends up being confusing if you have to use flags.flags.someProperty

2022-03-31 17:04 UTC, jhodak commented on packages/frontend/src/contexts/flagsContext.tsx
> +    const updateHookState = (key: string, value: unknown) => {
changing to updateFlagState

2022-03-31 17:09 UTC, Evalir commented on packages/frontend/src/contexts/flagsContext.tsx
> +    const [hookState, setHookState] = useState({
I would agree, but the `State` part is implied. The correct way to access it would be restructuring the flags property. `const { flags } = useFlags()`.

2022-03-31 18:24 UTC, jhodak commented on packages/frontend/src/contexts/flagsContext.tsx
> +)
updated - should be all set now

2022-03-31 18:31 UTC, jhodak commented on packages/frontend/src/contexts/flagsContext.tsx
> +    const updateHookState = (key: string, value: unknown) => {
changed to updateFlag

2022-03-31 18:32 UTC, jhodak commented on packages/frontend/src/contexts/flagsContext.tsx
> +    const [hookState, setHookState] = useState({
updated this with the names you specified above.

2022-03-31 18:53 UTC, jhodak commented on packages/frontend/src/contexts/flagsContext.tsx
> +
done

2022-03-31 23:22 UTC, Evalir approved these changes
This looks good to me!

2022-04-01 11:37 UTC, merged

2022-04-01 11:38 UTC, jhodak commented
Close T-1091